### ISSUE TITLE
Unknown options error

### ISSUE THREAD

**Issue by mjgs** [zdurham/s3-upload-github-action#8]
I have a workflow that is erroring with the following error

```
Unknown options: [path redacted]
```

I’ve redacted the path but it’s just the target path of the file.

The step is as follows:

```
      - name: Upload backup to s3 bucket
        if: ${{ contains(github.ref, 'main') || env.backup_enabled == 'yes' }}
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl private
        env:
          FILE: ${{ env.src_file }}
          AWS_REGION: 'eu-west-2'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_KEY: ${{ env.tgt_file }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
```

I have the very same configuration working in other repos. In fact it’s copy and pasted from a repo where it’s working without errors.

Why might this error occur?
